### PR TITLE
Moar items

### PR DESCRIPTION
**Pull request by warpdragon**
These are the 492 finished npc_abilities_override and 274 npc_items_custom for your consideration.
Big thanks to @Baumi @Relacibo for their amazing work writing these files, and @RamonNZ for debugging them. [edit: also Haganeko, CalmStorm, and anyone else I forgot to mention]

### CODE REVIEW

**Comment by Trildar** [comment]
I should have mentioned this earlier probably: https://moddota.com/forums/discussion/1415/combining-kv-files-using-base

Not really sure it would be worth the effort, but it would remove the need to rebuild the KV files whenever one of the individual files is changed, which I assume is currently the case.

**Comment by Relacibo** [comment]
I made a little script that should work:

    #!/bin/sh
    OUTPUT=npc_abilities_custom.txt
    FILEPATH=abilities_source
    OUTPUTFILEPATH=abilities
    
    mkdir -p $OUTPUTFILEPATH
    
    touch $OUTPUT
    
    for f in $FILEPATH/* ; do
        name=$(basename $f)
	    outputfile=$OUTPUTFILEPATH/$name
	    echo '"DOTAAbilities"' > $outputfile
	    echo '{' >> $outputfile
	    cat $f >> $outputfile
	    echo '}' >> $outputfile
	    echo "#base \"$OUTPUTFILEPATH/$name\"" >> $OUTPUT
    done

**Comment by warpdragon** [comment]
We're already ising such a script. Although it needs updating. Poke poke.

**Comment by chrisinajar** [comment]
Sweet mother of god

**Pull request merged**
