### PR TITLE
Custom team selection

### PR DESCRIPTION
**Pull request by salacryl**

### CODE REVIEW

**Comment by chrisinajar** [comment]
Looks awesome, can you just fix the conflicts so it'll merge cleanly?

**Comment by salacryl** [comment]
So conflicts resolved

**Comment by chrisinajar** [comment]
Can you exclude all the stuff from `game/panorama/images/`? they're just cached compiled assets, i forgot to add that to the gitignore before...

**Comment by salacryl** [comment]
and where to put them?

**Comment by Arhowk** [comment]
Apologies if you aren't using ripped assets but from my perspective it looks like your assets are all ripped for the loading screen

Firstly, I'd recommend talking with Baumi and whoever to make sure that you aren't operating over your jurisdiction

As someone who has [a decent bit of experience in using ripped assets](http://i.imgur.com/rVqp4GU.jpg) (that picture is insanely old) and has researched them, there are alot of legal loopholes you have to go through. My biggest recommendation is to 1) NOT maintain any content files in the repo and only maintain the game files and 2) to keep a list of all of the resources you have ripped and their authors in case you get a C&D so you have a list of what you have to replace.

If this is all original artwork than I'd recommend learning how to blur edges in Photoshop

~Jake

**Comment by salacryl** [comment]
Jake, this doesn't belong to a comment on a programmer commit. Just post it in discord if you have to and do a proper research (like: who is programmer, who is artist and where to find such information) BEFORE assuming anything.

Björn

**Comment by chrisinajar** [comment]
ping @salacryl, just need those compiled pngs removed from the folder in game and this is good to go. not sure if you forgot to push or never got around to fixing it.

**Comment by salacryl** [comment]
duh, I did, but didn-'t synced last time.

**Pull request merged**
