### PR TITLE
Fix for 6 level abilities in HUD #90

### PR DESCRIPTION
**Pull request by Trildar**
* Add dota_hud_ability_panel.css
  Lines 1676-1679 are the important bit. The rest is extracted from vanilla Dota.

Note: If Valve decide to change this file (in vanilla Dota) for whatever reason, it will likely need to be updated with the changes.

### CODE REVIEW

**Comment by Chronophylos** [comment]
Do we really need the whole file?

**Comment by Trildar** [comment]
Pretty sure it completely overrides rather than adding. Tried just putting the additional part and the UI gets messed up. You're welcome to double check though.

**Comment by chrisinajar** [comment]
CSS files are scoped to the dom which includes them, so to override system level dom styling you need to entirely replace the CSS files.......... UNLESS you edit the styling from JavaScript, in which case you can overwrite any system level styling and it works!

If we edit the styles from code then we don't need to worry about merging non-conflicting changes from valve, which is an inconvenient long term maintinence item. I haven't reviewed if this technique works in this particular case, let me know your results!

Thanks for the work!

**Comment by Trildar** [comment]
I did try the JavaScript method, which I mentioned briefly in #90. The issue is that the function that I had to change the styles caused lag, presumably due to DOM traversal. Adding to that, I think the styles don't reset when selecting another unit (haven't really tested though), which means the styling function needs to run on every selection change. We could just assume only the styling for the player's hero is important, but it could create minor visual glitches when viewing other units.

There might be some more efficient method, but I can't really think of one.

As a side note, I've completely forgotten to care about the separate unit query panel.

P.S. I'll probably put in the code I used later today when I'm actually on my computer.

**Pull request merged**
